# Generated by Django 5.2.1 on 2025-08-19 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Billing_App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='discount',
        ),
    ]
