# Generated by Django 5.2.1 on 2025-08-02 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billing_App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoiceitem',
            old_name='sub_total',
            new_name='price',
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
