# Generated by Django 5.2.1 on 2025-05-16 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Billing_App', '0002_rename_name_product_item_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Item_name',
            new_name='name',
        ),
    ]
