# Generated by Django 5.2.1 on 2025-07-28 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billing_App', '0005_userdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='item_id',
            new_name='product_id',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('Electronics', 'Electronics'), ('Clothing', 'Clothing'), ('Grocery', 'Grocery')], max_length=255, null=True),
        ),
    ]
