# Generated by Django 5.2.1 on 2025-08-03 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billing_App', '0005_alter_cartitem_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='Billing_App.cart'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
