# Generated by Django 5.2.1 on 2025-08-03 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billing_App', '0006_alter_cartitem_cart_alter_cartitem_sub_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
