# Generated by Django 5.2.1 on 2025-08-19 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Billing_App', '0006_cartitem_created_at_alter_cartitem_cart_and_more'),
    ]

    operations = [
    ]
