# Generated by Django 5.2.1 on 2025-08-06 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billing_App', '0008_invoice_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='balance',
        ),
        migrations.AddField(
            model_name='invoice',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('upi', 'UPI'), ('bank_transfer', 'Bank Transfer')], default='cash', max_length=50),
        ),
    ]
